import type { ProductionOrder } from '@/types/crm'
import type { QuoteCalculationItem } from '@/types/quotes'
import { formatCurrency } from '@/lib/sla'

export interface ParsedProductionItem {
  id: string
  name: string
  quantity?: number | string
  dimensions?: string
  material?: string
  additionals?: string
  unitPrice?: number | string
  totalPrice?: number | string
  notes?: string
}

export interface ParsedOrderDetails {
  items: ParsedProductionItem[]
  cleanNotes: string
  hasMultipleItems: boolean
  quoteId?: string
  quoteCode?: string
}

/**
 * Extracts quote ID / code from order notes or description tag if present
 */
export function extractQuoteLinkFromOrder(order: ProductionOrder): {
  quoteId?: string
  quoteCode?: string
} {
  const text = `${order.notes || ''} ${order.description || ''}`
  const quoteIdMatch = text.match(/\[QUOTE_ID:([a-zA-Z0-9_-]+)\]/)
  const quoteCodeMatch = text.match(/\[ORC:([a-zA-Z0-9_-]+)\]/)

  return {
    quoteId: quoteIdMatch ? quoteIdMatch[1] : undefined,
    quoteCode: quoteCodeMatch ? quoteCodeMatch[1] : undefined,
  }
}

/**
 * Strips technical quote link tags [QUOTE_ID:...] [ORC:...] from notes for clean UI display
 */
export function cleanOrderNotes(rawNotes?: string): string {
  if (!rawNotes) return ''
  let cleaned = rawNotes
    .replace(/\[QUOTE_ID:[^\]]+\]/g, '')
    .replace(/\[ORC:[^\]]+\]/g, '')
    .trim()

  // Clean empty lines or trailing "Origem: ..." if only tags were there
  cleaned = cleaned.replace(/\n\s*\n/g, '\n').trim()
  return cleaned
}

/**
 * Parses snapshot items from description or falls back to order root fields
 */
export function parseOrderItems(order: ProductionOrder): ParsedProductionItem[] {
  const description = order.description?.trim() || ''

  // Check if description has structured snapshot items generated by quoteToProductionService
  // e.g. "1. Product Name\n  - Quantidade: ...\n  - Medidas: ...\n\n2. Other Product..."
  if (description && /(?:^|\n)\d+\.\s+/.test(description)) {
    // Split by numbered items
    const rawBlocks = description.split(/(?:^|\n)(?=\d+\.\s+)/).filter((b) => b.trim())

    if (rawBlocks.length > 0) {
      const parsedItems: ParsedProductionItem[] = rawBlocks.map((block, idx) => {
        const lines = block
          .split('\n')
          .map((l) => l.trim())
          .filter(Boolean)
        const headerLine = lines[0] || ''
        // Remove number prefix "1. ", "2. ", etc.
        const name = headerLine.replace(/^\d+\.\s*/, '').trim() || `Item ${idx + 1}`

        let quantity: string | undefined
        let dimensions: string | undefined
        let material: string | undefined
        let additionals: string | undefined
        let unitPrice: string | undefined
        let totalPrice: string | undefined
        let notes: string | undefined

        for (let i = 1; i < lines.length; i++) {
          const line = lines[i].replace(/^-\s*/, '').trim()
          if (!line) continue

          if (/^Quantidade:\s*/i.test(line)) {
            quantity = line.replace(/^Quantidade:\s*/i, '').trim()
          } else if (/^Medidas:\s*/i.test(line)) {
            dimensions = line.replace(/^Medidas:\s*/i, '').trim()
          } else if (/^Material:\s*/i.test(line)) {
            material = line.replace(/^Material:\s*/i, '').trim()
          } else if (/^Acabamentos\/Adicionais:\s*/i.test(line)) {
            additionals = line.replace(/^Acabamentos\/Adicionais:\s*/i, '').trim()
          } else if (/^Acabamentos:\s*/i.test(line)) {
            additionals = line.replace(/^Acabamentos:\s*/i, '').trim()
          } else if (/Valor Unit:/i.test(line) || /Total Item:/i.test(line)) {
            // e.g. "Valor Unit: R$ 25,00 | Total Item: R$ 25,00"
            const parts = line.split('|')
            parts.forEach((p) => {
              const trimmed = p.trim()
              if (/Valor Unit:/i.test(trimmed)) {
                unitPrice = trimmed.replace(/Valor Unit:\s*/i, '').trim()
              } else if (/Total Item:/i.test(trimmed)) {
                totalPrice = trimmed.replace(/Total Item:\s*/i, '').trim()
              }
            })
          } else if (/^Observação do item:\s*/i.test(line)) {
            notes = line.replace(/^Observação do item:\s*/i, '').trim()
          } else if (!notes && !/^Valor/i.test(line)) {
            // Additional custom line
            notes = line
          }
        }

        return {
          id: `item_${idx + 1}`,
          name,
          quantity,
          dimensions,
          material,
          additionals,
          unitPrice,
          totalPrice,
          notes,
        }
      })

      if (parsedItems.length > 0) {
        return parsedItems
      }
    }
  }

  // Fallback 1: If product field has multiple comma-separated items with matching comma-separated dimensions
  // e.g. product = "Adesivo Personalizado, Adesivo Personalizado", but description didn't match regex
  if (order.product && order.product.includes(', ')) {
    const names = order.product
      .split(', ')
      .map((n) => n.trim())
      .filter(Boolean)
    const dims = order.dimensions ? order.dimensions.split(', ').map((d) => d.trim()) : []

    if (names.length > 1) {
      return names.map((name, idx) => ({
        id: `item_split_${idx + 1}`,
        name: name.replace(/^\d+x\s*/, ''),
        quantity: name.match(/^(\d+)x\s*/)?.[1] || 1,
        dimensions: dims[idx] || undefined,
        material: undefined,
        additionals: undefined,
        unitPrice: undefined,
        totalPrice: undefined,
        notes: undefined,
      }))
    }
  }

  // Fallback 2: Single item built from top-level order properties
  return [
    {
      id: 'item_single_1',
      name: order.product || 'Produto sob medida',
      quantity: order.quantity ? `${order.quantity} un` : undefined,
      dimensions: order.dimensions || undefined,
      material: undefined,
      additionals: undefined,
      unitPrice: undefined,
      totalPrice: order.total_value ? formatCurrency(order.total_value) : undefined,
      notes: order.description || undefined,
    },
  ]
}

/**
 * Converts quote calculation items into ParsedProductionItem[]
 */
export function convertQuoteItemsToParsed(items: QuoteCalculationItem[]): ParsedProductionItem[] {
  if (!items || !Array.isArray(items) || items.length === 0) return []

  return items.map((it, idx) => {
    let dimensions: string | undefined
    if (it.width && it.height && it.width > 0 && it.height > 0) {
      dimensions = `${it.width.toFixed(2).replace('.', ',')} × ${it.height.toFixed(2).replace('.', ',')} m`
      if (it.total_area) {
        dimensions += ` (${it.total_area.toFixed(2).replace('.', ',')} m²)`
      }
    } else if (it.linear_meters && it.linear_meters > 0) {
      dimensions = `${it.linear_meters.toFixed(2).replace('.', ',')} m lineares`
    }

    let additionals: string | undefined
    if (Array.isArray(it.additionals) && it.additionals.length > 0) {
      const adds = it.additionals
        .map((a) => (a.quantity && a.quantity > 1 ? `${a.name} (${a.quantity} un)` : a.name))
        .filter(Boolean)
      if (adds.length > 0) {
        additionals = adds.join(', ')
      }
    }

    const unitVal = it.applied_unit_price || it.calculated_unit_price || 0
    const totalItemVal =
      it.item_total_sale !== undefined && it.item_total_sale !== null
        ? it.item_total_sale
        : unitVal * (it.quantity || 1)

    return {
      id: it.id || `quote_item_${idx + 1}`,
      name: it.product_name || 'Item do Pedido',
      quantity: it.quantity ? `${it.quantity} un` : undefined,
      dimensions,
      material: it.material_name || undefined,
      additionals,
      unitPrice: unitVal > 0 ? formatCurrency(unitVal) : undefined,
      totalPrice: totalItemVal > 0 ? formatCurrency(totalItemVal) : undefined,
      notes: it.notes?.trim() || undefined,
    }
  })
}
